import { createClient } from '@supabase/supabase-js'
import * as dotenv from 'dotenv'

dotenv.config({ path: '.env.local' })

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
)

const courses = [
  {
    title: 'Siemens TIA Portal: Advanced PLC Programming',
    slug: 'siemens-tia-portal',
    short_description: 'Master industrial automation with Siemens S7-1200/1500 using TIA Portal V18.',
    description: 'A comprehensive professional course covering Siemens TIA Portal from foundations to advanced applications. Hands-on training with S7-1200 and S7-1500 PLCs, HMI configuration, and real-world industrial projects.',
    price: 299,
    currency: 'USD',
    level: 'Advanced',
    duration_hours: 40,
    format: 'In-person + lab',
    language: 'English / Arabic',
    cohort_size: '8–14 trainees',
    certificate: 'Matrix EA',
    category: 'PLC',
    is_published: true,
    prerequisites: 'Basic electrical knowledge, introductory PLC experience',
    modules: [
      { number: '01', title: 'TIA Portal Environment & Project Setup', description: 'Interface navigation, hardware configuration, device setup wizard' },
      { number: '02', title: 'S7-1200 / S7-1500 Hardware Architecture', description: 'CPU specs, signal modules, communication modules, power supply selection' },
      { number: '03', title: 'Data Types, Tags & Memory Areas', description: 'DB blocks, I/O mapping, retentive vs. non-retentive memory, PLC tags' },
      { number: '04', title: 'Ladder Diagram (LAD) Programming', description: 'Contacts, coils, timers, counters, comparison instructions' },
      { number: '05', title: 'Function Block Diagram (FBD) & STL', description: 'FBD logic for process control, structured text for complex algorithms' },
      { number: '06', title: 'Function Blocks & Reusable Libraries', description: 'Creating FBs, FB instances, multi-instance FBs, library management' },
      { number: '07', title: 'Motion Control Basics', description: 'Axis configuration, homing routines, velocity/position control blocks' },
      { number: '08', title: 'HMI Development with WinCC', description: 'Creating screens, dynamic elements, alarms, trends, user management' },
      { number: '09', title: 'PROFINET & Industrial Communication', description: 'PROFINET IO, PROFIBUS DP, Modbus TCP, OPC UA configuration' },
      { number: '10', title: 'PID Control & Analog I/O', description: 'PID_Compact instruction, tuning methods, 4–20mA signal conditioning' },
      { number: '11', title: 'Fault Diagnostics & Troubleshooting', description: 'Online monitoring, cross-reference, force table, diagnostics buffer' },
      { number: '12', title: 'Capstone Project: Packaging Line', description: 'Full conveyor + sorting station PLC program with HMI and SCADA integration' },
    ],
    outcomes: [
      'Configure and program Siemens S7-1200 and S7-1500 PLCs from scratch',
      'Build HMI screens using WinCC Advanced / Comfort',
      'Implement PROFINET communication networks',
      'Design and tune PID control loops',
      'Diagnose faults and use TIA Portal diagnostic tools professionally',
    ],
    featured_image: null,
  },
  {
    title: 'Delta PLC Programming',
    slug: 'delta-plc',
    short_description: 'Master Delta DVP and AS series PLC programming with ISPSoft and DIADesigner.',
    description: 'Comprehensive training on Delta DVP and AS300 series PLCs — from wiring and I/O configuration to advanced ladder/structured text programs. Covers Delta HMI integration and communication protocols.',
    price: 199,
    currency: 'USD',
    level: 'Intermediate',
    duration_hours: 24,
    format: 'In-person + lab',
    language: 'English / Arabic',
    cohort_size: '8–14 trainees',
    certificate: 'Matrix EA',
    category: 'PLC',
    is_published: true,
    prerequisites: 'Basic electrical knowledge, relay logic understanding',
    modules: [
      { number: '01', title: 'Delta PLC Product Range & Selection', description: 'DVP series vs AS300, model selection criteria, I/O expansion' },
      { number: '02', title: 'ISPSoft / DIADesigner Environment', description: 'Project setup, hardware configuration, I/O module wiring' },
      { number: '03', title: 'Ladder & SFC Programming', description: 'Timers, counters, data move, comparison, arithmetic' },
      { number: '04', title: 'Structured Text (IEC 61131-3)', description: 'ST syntax, loops, conditionals, function blocks in DIADesigner' },
      { number: '05', title: 'Delta HMI Integration', description: 'DOP-W series HMI configuration, tag linking, alarm management' },
      { number: '06', title: 'Communication — Modbus & Delta Link', description: 'RS-485 Modbus RTU master/slave, Delta Link protocol for drives' },
      { number: '07', title: 'Motion & Pulse Output', description: 'High-speed pulse output for stepper/servo, DRVX instructions' },
      { number: '08', title: 'Project: Water Treatment Panel', description: 'Full dosing pump and level control system with Delta PLC and HMI' },
    ],
    outcomes: [
      'Program Delta DVP and AS300 series PLCs confidently',
      'Configure Delta HMI panels and link tags',
      'Implement Modbus RTU communication',
      'Control motion via pulse output to stepper and servo drives',
    ],
    featured_image: null,
  },
  {
    title: 'EPLAN Electric P8',
    slug: 'eplan-electric-p8',
    short_description: 'Create professional electrical engineering documentation with EPLAN Electric P8.',
    description: 'Professional EPLAN Electric P8 training for electrical engineers. Learn to design schematic diagrams, generate BOMs, create terminal diagrams, and manage projects according to IEC standards.',
    price: 229,
    currency: 'USD',
    level: 'Intermediate',
    duration_hours: 32,
    format: 'In-person + lab',
    language: 'English / Arabic',
    cohort_size: '8–14 trainees',
    certificate: 'Matrix EA',
    category: 'Electrical',
    is_published: true,
    prerequisites: 'Electrical engineering background, familiarity with circuit diagrams',
    modules: [
      { number: '01', title: 'EPLAN Environment & Project Structure', description: 'Interface, project properties, page types, settings configuration' },
      { number: '02', title: 'Schematic Design Fundamentals', description: 'Drawing schematics, placing symbols, connections, T-connections' },
      { number: '03', title: 'Symbol Libraries & Part Management', description: 'Creating custom symbols, part master data, manufacturer assignments' },
      { number: '04', title: 'Power Distribution Diagrams', description: 'Main circuits, motor starters, VFD circuits, bus bars' },
      { number: '05', title: 'Control Circuit Design', description: 'PLC I/O diagrams, relay circuits, safety circuits, interlocks' },
      { number: '06', title: 'Terminal & Cable Diagrams', description: 'Terminal strips, cable routing diagrams, shielded cables' },
      { number: '07', title: 'Reports & BOM Generation', description: 'Device lists, cable lists, terminal diagrams, cabinet layouts' },
      { number: '08', title: 'Project: Industrial Control Panel', description: 'Complete MCC panel documentation from power to control circuits' },
    ],
    outcomes: [
      'Create professional electrical schematics to IEC standards',
      'Design complete panel documentation packages',
      'Generate automatic BOMs, terminal lists, and cable schedules',
      'Manage EPLAN parts database and symbol libraries',
    ],
    featured_image: null,
  },
  {
    title: 'SCADA & HMI Development',
    slug: 'scada-hmi',
    short_description: 'Build professional SCADA systems and HMI applications for industrial process control.',
    description: 'Hands-on SCADA and HMI development course covering Wonderware InTouch, Ignition, and WinCC SCADA. Design operator interfaces, historian configuration, alarming, and reporting for industrial plants.',
    price: 279,
    currency: 'USD',
    level: 'Advanced',
    duration_hours: 36,
    format: 'In-person + lab',
    language: 'English / Arabic',
    cohort_size: '8–14 trainees',
    certificate: 'Matrix EA',
    category: 'SCADA',
    is_published: true,
    prerequisites: 'PLC programming experience, basic networking knowledge',
    modules: [
      { number: '01', title: 'SCADA Architecture & Standards', description: 'SCADA topology, ISA-95, Purdue model, OT security fundamentals' },
      { number: '02', title: 'HMI Design Principles', description: 'High-performance HMI (EEMUA 201), colour usage, navigation design' },
      { number: '03', title: 'OPC UA & Data Acquisition', description: 'OPC UA server/client configuration, tag browsing, data quality' },
      { number: '04', title: 'Ignition Platform Introduction', description: 'Gateway setup, designers, vision vs perspective modules' },
      { number: '05', title: 'Screen Development — Process Graphics', description: 'P&ID-style graphics, animated components, real-time data binding' },
      { number: '06', title: 'Alarming & Alarm Management', description: 'Alarm shelving, acknowledgment, priority levels, ISA-18.2 compliance' },
      { number: '07', title: 'Historian & Trends', description: 'Tag historian configuration, trend charts, calculated tags, reporting' },
      { number: '08', title: 'Scripting & Automation', description: 'Python scripting in Ignition, gateway event scripts, tag change scripts' },
      { number: '09', title: 'Security & Access Control', description: 'User roles, authentication, zone segmentation, audit trails' },
      { number: '10', title: 'Redundancy & High Availability', description: 'Redundant gateways, UPS integration, failover testing' },
      { number: '11', title: 'Mobile & Web Perspective Modules', description: 'Responsive HMI for tablets and mobile devices' },
      { number: '12', title: 'Capstone: Water Utility SCADA', description: 'Full SCADA for multi-pump station with historian and reports' },
    ],
    outcomes: [
      'Design high-performance HMI screens following industry standards',
      'Configure OPC UA data acquisition from PLCs',
      'Build alarm management systems per ISA-18.2',
      'Set up tag historian and generate operational reports',
      'Implement user security and access control in SCADA',
    ],
    featured_image: null,
  },
  {
    title: 'Battery Systems & Energy Storage',
    slug: 'battery-systems',
    short_description: 'Understand, size, install, and commission industrial battery energy storage systems.',
    description: 'Technical training on lithium-ion and lead-acid battery systems for industrial and solar applications. Covers BMS configuration, system sizing, protection coordination, and maintenance procedures.',
    price: 179,
    currency: 'USD',
    level: 'Intermediate',
    duration_hours: 20,
    format: 'In-person + lab',
    language: 'English / Arabic',
    cohort_size: '8–14 trainees',
    certificate: 'Matrix EA',
    category: 'Energy',
    is_published: true,
    prerequisites: 'Electrical fundamentals, basic DC circuit knowledge',
    modules: [
      { number: '01', title: 'Battery Technologies & Chemistries', description: 'Li-Ion (LFP, NMC), lead-acid, supercapacitors — comparison and use cases' },
      { number: '02', title: 'Battery Management System (BMS)', description: 'Cell balancing, SOC estimation, protection circuits, CAN bus communication' },
      { number: '03', title: 'System Sizing & Design', description: 'Load profiling, autonomy calculation, C-rate selection, derating factors' },
      { number: '04', title: 'DC Wiring & Protection', description: 'Fusing, disconnects, cable sizing, arc flash considerations' },
      { number: '05', title: 'Inverter/Charger Integration', description: 'Grid-tied vs. off-grid topologies, EPS mode, generator interaction' },
      { number: '06', title: 'Commissioning & Testing', description: 'Acceptance testing, capacity test procedure, thermal imaging' },
      { number: '07', title: 'O&M & Troubleshooting', description: 'Preventive maintenance schedule, fault codes, replacement procedures' },
      { number: '08', title: 'Lab: Industrial BESS Commissioning', description: 'Hands-on commissioning of a 10kWh LFP system with grid-tie inverter' },
    ],
    outcomes: [
      'Select appropriate battery chemistry for given application',
      'Size a battery storage system from load data',
      'Configure BMS communication and protection parameters',
      'Commission and test a battery energy storage system',
      'Perform preventive maintenance and diagnose faults',
    ],
    featured_image: null,
  },
  {
    title: 'Veichi VFD & Servo Systems',
    slug: 'veichi-vfd-servo',
    short_description: 'Install, configure, and troubleshoot Veichi variable frequency drives and servo systems.',
    description: 'Hands-on training covering Veichi AC300/AC310 VFDs and SD700 servo drives. Parameter configuration, control mode selection, PLC communication, and real-world troubleshooting.',
    price: 149,
    currency: 'USD',
    level: 'Beginner',
    duration_hours: 16,
    format: 'In-person + lab',
    language: 'English / Arabic',
    cohort_size: '8–14 trainees',
    certificate: 'Matrix EA',
    category: 'Drives',
    is_published: true,
    prerequisites: 'Basic electrical knowledge, motor fundamentals',
    modules: [
      { number: '01', title: 'VFD Operating Principles', description: 'V/f control, vector control, PWM technology, motor compatibility' },
      { number: '02', title: 'Veichi AC300/AC310 Hardware', description: 'Model selection, power wiring, EMC filters, brake resistors' },
      { number: '03', title: 'Parameter Configuration', description: 'Motor autotuning, control mode selection, frequency reference sources' },
      { number: '04', title: 'Digital & Analog I/O', description: 'Multi-speed presets, PID feedback, analog reference scaling' },
      { number: '05', title: 'Communication — Modbus RTU', description: 'RS-485 wiring, Modbus register map, PLC speed control program' },
      { number: '06', title: 'Servo Fundamentals & SD700 Setup', description: 'Servo vs VFD, encoder feedback, position/velocity/torque modes' },
      { number: '07', title: 'Motion Profiles & Tuning', description: 'Gain tuning, S-curve ramps, electronic gearing' },
      { number: '08', title: 'Troubleshooting Lab', description: 'Fault code diagnosis, oscilloscope traces, drive replacement procedure' },
    ],
    outcomes: [
      'Wire and commission Veichi AC300 VFDs',
      'Configure motor autotuning and control modes',
      'Set up PLC-VFD communication via Modbus RTU',
      'Install and tune Veichi SD700 servo drives',
      'Diagnose and resolve common VFD faults',
    ],
    featured_image: null,
  },
  {
    title: 'VFD Fundamentals',
    slug: 'vfd-fundamentals',
    short_description: 'Learn the principles and practical operation of variable frequency drives.',
    description: 'Foundation course for engineers and technicians entering the world of variable speed drives. Covers AC motor theory, VFD topology, application selection, installation, and maintenance.',
    price: 129,
    currency: 'USD',
    level: 'Beginner',
    duration_hours: 12,
    format: 'In-person + lab',
    language: 'English / Arabic',
    cohort_size: '8–14 trainees',
    certificate: 'Matrix EA',
    category: 'Drives',
    is_published: true,
    prerequisites: 'Basic electrical theory, familiarity with AC motors',
    modules: [
      { number: '01', title: 'AC Motor Theory Review', description: 'Induction motor operation, slip, torque-speed curves, efficiency classes' },
      { number: '02', title: 'VFD Topology & Components', description: 'Rectifier, DC bus, inverter stage, IGBT switching, power factor' },
      { number: '03', title: 'VFD Selection Criteria', description: 'Load type (constant vs. variable torque), duty cycle, overload ratings' },
      { number: '04', title: 'Installation & Wiring Best Practices', description: 'Enclosure ratings, cable routing, EMC, grounding, shielding' },
      { number: '05', title: 'Basic Parameter Setup', description: 'Motor nameplate data entry, start/stop methods, ramp times' },
      { number: '06', title: 'Application Examples', description: 'Pump, fan, conveyor, and compressor drive configurations' },
      { number: '07', title: 'Maintenance & Fault Diagnosis', description: 'Preventive maintenance, common faults, fault code interpretation' },
      { number: '08', title: 'Practical Lab Session', description: 'Hands-on wiring, commissioning, and fault injection exercise' },
    ],
    outcomes: [
      'Explain VFD operating principles and power electronics',
      'Select the correct VFD for a given motor application',
      'Wire and commission a VFD following best practices',
      'Configure essential VFD parameters from motor nameplate data',
      'Perform preventive maintenance and fault diagnosis',
    ],
    featured_image: null,
  },
]

async function seed() {
  console.log('Seeding courses...')
  for (const course of courses) {
    const { error } = await supabase
      .from('courses')
      .upsert(course, { onConflict: 'slug' })
    if (error) {
      console.error(`Failed to seed "${course.title}":`, error.message)
    } else {
      console.log(`✓ ${course.title}`)
    }
  }
  console.log('Done.')
}

seed().catch(console.error)
